service: even_blog
image: evenzhang0802/even_blog
servers:
  web:
    hosts:
      - 134.175.233.100
    options:
      # add the host ip, so the containers can reach each other without docker-compose by using
      # postgres://host.docker.internal/.. etc.
      add-host: host.docker.internal:host-gateway
registry:
  username: evenzhang0802
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  clear:
    RAILS_ENV: production
    POSTGRES_HOST: host.docker.internal
    POSTGRES_DB: even_blog
  secret:
    - SECRET_KEY_BASE
    - POSTGRES_USER
    - POSTGRES_PASSWORD
ssh:
  user: ubuntu
traefik:
  options:
    publish:
      - "443:443"
  args:
    entrypoints.web.address: ':80'
    entryPoints.websecure.address: ":443"
accessories:
  db:
     image: postgres:15.3-alpine
     host: 134.175.233.100
     port: 5432
     env:
       clear:
         POSTGRES_DB: even_blog
       secret:
         - POSTGRES_USER
         - POSTGRES_PASSWORD
     directories:
       - data:/var/lib/postgresql/data
