name: Deploy with Capistrano

on:
  push:
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - run: bundle exec cap production deploy
      - run: bundle exec cap production custom:run_assets_precompile
